### ISSUE TITLE
TMPDIR not being created

### ISSUE THREAD

**Issue by elrido** [rugk/gittools#4]
Unfortunately, at least with the mktemp version on my distro (mktemp (GNU coreutils) 8.32) it refuses to create a subdirectory, so f10c55c would only work if /tmp/signrelease happened to exist (my temporary workaround to get the script going).

Since mktemp may not use /tmp, depending on the environment, I could think of multiple solutions:
1. revert  f10c55c (would be a pity, but I never minded the name and the pattern ensures they are all unique)
2. mkdir /tmp/signrelease, then run mktemp with `-p /tmp` - this is a bit risky, since there may be reasons some system doesn't use /tmp
3. replicate the "use $TMPDIR if set, else /tmp" logic for the mkdir, before calling the mktemp as is (no -p)

**Comment by rugk** [comment]
Hmm but wait, why does not it do so? AFAIK and I looked at the manage again, `mktemp` should create the dir. Obviously one could do `mkdir -p` again but what is the point?

**Comment by elrido** [comment]
It will only create one dir, not a tree (=first signrelease, then "${project}-${tag}-XXXXXXXXXX" within it). It refuses with:

```sh
$ mktemp -d foo/bar-XXX
mktemp: failed to create directory via template 'foo/bar-XXX': No such file or directory
```

**Comment by elrido** [comment]
Thank you!
